# Generated by Django 4.2.6 on 2023-10-31 02:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firebase_user_id', models.CharField(max_length=255)),
                ('verify_key', models.CharField(max_length=255)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
