# Generated by Django 4.2.6 on 2023-10-31 07:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=255)),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('subscription_id', models.CharField(max_length=255)),
                ('plan_type', models.CharField(max_length=255)),
                ('primary_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.users')),
            ],
        ),
    ]
