# Generated by Django 4.2.6 on 2023-10-31 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_todos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_key', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sender_email', models.EmailField(max_length=254)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.organizations')),
            ],
        ),
    ]
